# Generated by Django 3.0.14 on 2021-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
